# Generated by Django 4.1.7 on 2023-03-20 16:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_category_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(default="test", verbose_name="Content"),
            preserve_default=False,
        ),
    ]
