# Generated by Django 4.1.7 on 2023-03-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_content"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="content", new_name="body",),
    ]
